### ISSUE TITLE
feat: GeoIP interceptor config expansion

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#173]
# Description

Present version of GeoIP interceptor only allows taking in a list of countries for blocking the requests, this should be expanded to allow for a lot more ways to define the config:
1. List of continents
2. List of countries
3. List of states
4. List of districts
5. List of blocks (Refer to GeoQuery for the levels at which these things can be found)
6. GeoFence
7. List of coordinates 
8. Range of coordinates

On top of the above things we also need to give the user the ability to choose whether this list is of the regions where to allow the requests from or where to block the requests from.

## Tasks
- [ ] Figure out the exhaustive list of things which can be a part of this list
- [ ] Design the service
- [ ] Implementation
- [ ] Test Case addition
