### ISSUE TITLE
BHASAI - Backend Reusable Components

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#180]
# To-Do

- [ ] Cache - https://github.com/BharatSahAIyak/inbound-js/tree/scaling/src/cache
- [ ] BatchWorker - https://github.com/BharatSahAIyak/inbound-js/tree/scaling/src/batchWorker
- [ ] Message ACK -  https://github.com/BharatSahAIyak/transport-socket/blob/364d0fc8444ad1f383cbf1e681670cce7b85d382/src/app.controller.ts#L31
- [ ] Auth - https://github.com/BharatSahAIyak/nodehub/blob/dev/src/interceptors/addUserDetails.interceptor.ts

**Comment by chinmoy12c** [comment]
Cache - https://github.com/BharatSahAIyak/inbound-js/tree/scaling/src/cache
BatchWorker - https://github.com/BharatSahAIyak/inbound-js/tree/scaling/src/batchWorker
Message ACK -  https://github.com/BharatSahAIyak/transport-socket/blob/364d0fc8444ad1f383cbf1e681670cce7b85d382/src/app.controller.ts#L31
Auth - https://github.com/BharatSahAIyak/nodehub/blob/dev/src/interceptors/addUserDetails.interceptor.ts
