### ISSUE TITLE
[stencil] choose between fastify and express

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#24]
## Description

Currently stencil ships with the base app running fastify, we plan to give the user option to choose between fastify or express.

## Tasks
- [ ] create sample projects for express
- [ ] modify the schematics to hold the base app for both
- [ ] modify the stencil-cli to give the option to bootstrap what's asked

**Comment by techsavvyash** [comment]
Stencil is opinionated so, not adding support for this right now.
