### ISSUE TITLE
[docs] Doc Generation

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#9]
## ToDo:

- [ ] Figure out how to automatically generate docs
    - [ ] for `stencil`
    - [ ] for `stencil-cli` 
- [ ] Add the feature and allow for autogeneration
- [ ] Allow for automatic deploys on vercel -- this will be handled automatically after first deployment.

**Comment by Savio629** [comment]
What kind of docs are we looking here?
The docs will be generated on a website which will be deployed on vercel?
